version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5433;Database=characterDB;Username=postgres;Password=1234;

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=characterDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
